name: build-documentation

on:
  push:
    branches:
      - "development"
  workflow_dispatch:

jobs:
  build-docc:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: "Cleanup build folder"
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./


      - name: "Install swiftlint"
        run: |
          brew install swiftlint

      - name: "Select Xcode (Default)"
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Runner environment
        run: |
          echo "MacOS Version"
          sw_vers
          echo "Toolchain version"
          swift -version
          echo "SwiftLint (version)"
          swiftlint version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create folder for generated documentation
        run: mkdir -p docs

      - name: Build Documentation
        run: |
          xcodebuild docbuild \
            -scheme "Aurora Editor" \
            -destination generic/platform=macOS \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          DOCURL=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')
          echo "docs.auroraeditor.com" > CNAME
          echo "{\"meta\":{\"title\":\"$DOCURL Documentation\"}}" > theme-settings.json
          echo "<script>window.location.href = (document.location.host == 'auroraeditor.github.io' ? '/AuroraEditor' : '') + '/documentation/$DOCURL/'.toLowerCase();</script>" > index.html
          git init -b documentation
          git add -A .
          git commit -m "Deploy documentation"
          git push -f "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" documentation:documentation

      - name: Cleanup runner
        if: always()
        run: |
          if [ -d "${{ github.workspace }}" ]; then
            cd "${{ github.workspace }}"
            rm -rf *
          fi
